from dataclasses import dataclass, field
from datetime import date
from typing import List, Dict, Optional

@dataclass
class Owner:
    name: str
    contact: Optional[str] = None
    preferences: Dict[str, str] = field(default_factory=dict)

    def add_preference(self, key: str, value: str) -> None:
        self.preferences[key] = value

    def update_name(self, new_name: str) -> None:
        self.name = new_name

@dataclass
class Pet:
    name: str
    species: str
    breed: Optional[str] = None
    food_type: Optional[str] = None
    collar_number: Optional[str] = None

    def set_food_type(self, food_type: str) -> None:
        self.food_type = food_type

    def set_collar_number(self, collar_number: str) -> None:
        self.collar_number = collar_number

@dataclass
class Task:
    title: str
    duration_minutes: int
    notes: Optional[str] = None

    def set_duration(self, minutes: int) -> None:
        self.duration_minutes = minutes

@dataclass
class Schedule:
    owner: Owner
    pet: Pet
    tasks: List[Task] = field(default_factory=list)
    date: date = field(default_factory=date.today)
    plan: List[Task] = field(default_factory=list)

    def set_date(self, schedule_date: date) -> None:
        self.date = schedule_date

    def add_task(self, task: Task) -> None:
        self.tasks.append(task)

    def build_plan(self) -> List[Task]:
        # Priority is implied by shorter duration as design change
        self.plan = sorted(self.tasks, key=lambda t: t.duration_minutes)
        return self.plan

    def explain_plan(self) -> str:
        if not self.plan:
            return "No plan generated yet."
        return "\n".join(
            f"{i+1}. {task.title} ({task.duration_minutes}m)"
            for i, task in enumerate(self.plan)
        )

class DisplayChart:
    def __init__(self, schedule: Schedule):
        self.schedule = schedule

    def display(self) -> str:
        table = self.render_table()
        explain = self.render_explanation()
        return f"{table}\n\n{explain}"

    def render_table(self) -> str:
        if not self.schedule.plan:
            return "No schedule to display."
        rows = [
            f"{i+1}. {task.title} - {task.duration_minutes}m"
            for i, task in enumerate(self.schedule.plan)
        ]
        return "\n".join(rows)

    def render_explanation(self) -> str:
        return self.schedule.explain_plan()

# Test class suggestions (autogenerated placeholder for unit tests)
class PawPalTests:
    def test_schedule_builds_by_duration(self):
        pass

    def test_empty_task_list(self):
        pass

    def test_display_chart_outputs(self):
        pass
